### ISSUE TITLE
Implement Crossover book stuff

### ISSUE THREAD

**Issue by guswadsworth12** [WookieeMatt/Essence20#354]
Review and determine what needs to be added for the crossover book.

**Comment by JFranklin3000** [comment]
For Crossover it would just need a dialog with the ability to turn on options for sheets (spellcasting, morphing, and alt mode). I am thinking that would be enable hidden tabs and use the defense-pr instead of defense on the actor sheet (or we get the morph and transform buttons to work and turn that on). I have to code already for the Crossover button on the top of the sheet.
